apiVersion: v3
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.13.0
  - name: application
    repository: file://charts/application
    version: 0.1.0
    condition: application.enabled
  - name: authentication
    repository: file://charts/authentication
    version: 0.1.0
    condition: authentication.enabled
