global: 
  host: iot.ecosystem.com
  image:
    prefix: registry.iot.io
  replicaCount: 1
  envRef: 
    APPLICATION_ID: metadata.name

application:
  enabled: true
  image:
    repository: application
    tag: latest
  services:
    - type: ClusterIP
      specs:
        - name: application
          port: 3000
          targetPort: 3000

authentication:
  enabled: true
  image:
    repository: authentication
    tag: latest
  services:
    - type: ClusterIP
      specs:
        - name: authentication
          port: 4000
          targetPort: 4000

ingress:
  enabled: false
#   paths:
#     - name: api-admin
#       path: /api-admin/?(.*)
#       servicePort: 3000
#     - name: service-datasource
#       path: /service-datasource/?(.*)
#       servicePort: 4000
